name: CI/CD - Build Docker Image

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false  # اجعلها true إذا كنت تريد رفع الصورة تلقائياً إلى Docker Hub (يتطلب إعداد الأسرار Secrets)
        tags: cosmic-324:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
